//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPiHW_ShikhaSingh
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Student
    {
        [Required]
        public int ID { get; set; }
        [Required]
        public string NAME { get; set; }
        [Required]
        public Nullable<int> AGE { get; set; }
        [Required]
        public string ADDRESS { get; set; }
        [Required]
        [EmailAddress]
        public string EMAIL { get; set; }
    }
}
